version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_PASSWORD: BlaBlaBla
      POSTGRES_DB: labBack
  